# Generated by Django 3.0.5 on 2020-12-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assiged_users',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9),
        ),
    ]
