# Generated by Django 3.0.5 on 2020-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20201213_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('OH', 'On Hold'), ('OT', 'On Track'), ('CA', 'Cancelled'), ('BE', 'Behind')], default='NS', max_length=10),
        ),
    ]
