# Generated by Django 3.0.5 on 2020-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(to='apps.Tag'),
        ),
    ]
