# Generated by Django 3.0.5 on 2020-12-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_project_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
